### ISSUE TITLE
Sketch-to-Art - Synthesizing Stylized Art Images From Sketches 

### ISSUE THREAD

**Issue by silky** [BraneShop/showreel#505]
![image](https://user-images.githubusercontent.com/129525/75728485-06b27100-5d3c-11ea-9618-d6f050c68f0d.png)

https://arxiv.org/pdf/2002.12888.pdf

**Comment by silky** [comment]
https://create.playform.io/sketch-to-image

**Comment by tanbuinhat** [comment]
Hi do you have complete code for this paper

**Comment by tanbuinhat** [comment]
Hi do you have code for this paper
